let studentsData = [
  { name: "John Smith", class: "Class 1", id: 1, present: false },
  { name: "Emily Johnson", class: "Class 1", id: 2, present: false },
  { name: "Michael Williams", class: "Class 1", id: 3, present: false },
  { name: "Sarah Brown", class: "Class 1", id: 4, present: false },
  { name: "David Jones", class: "Class 1", id: 5, present: false },
  { name: "Jennifer Davis", class: "Class 1", id: 6, present: false },
  { name: "James Miller", class: "Class 1", id: 7, present: false },
  { name: "Jessica Wilson", class: "Class 1", id: 8, present: false },
  { name: "Robert Taylor", class: "Class 1", id: 9, present: false },
  { name: "Lauren Martinez", class: "Class 1", id: 10, present: false },

  { name: "Matthew Anderson", class: "Class 2", id: 11, present: false },
  { name: "Samantha Thomas", class: "Class 2", id: 12, present: false },
  { name: "Christopher Garcia", class: "Class 2", id: 13, present: false },
  { name: "Ashley Hernandez", class: "Class 2", id: 14, present: false },
  { name: "Daniel Martinez", class: "Class 2", id: 15, present: false },
  { name: "Elizabeth Lopez", class: "Class 2", id: 16, present: false },
  { name: "Ryan Wilson", class: "Class 2", id: 17, present: false },
  { name: "Taylor Gonzalez", class: "Class 2", id: 18, present: false },
  { name: "Joshua Lee", class: "Class 2", id: 19, present: false },
  { name: "Amanda Perez", class: "Class 2", id: 20, present: false },

  { name: "Ethan Rodriguez", class: "Class 3", id: 21, present: false },
  { name: "Madison Garcia", class: "Class 3", id: 22, present: false },
  { name: "Noah Martinez", class: "Class 3", id: 23, present: false },
  { name: "Chloe Hernandez", class: "Class 3", id: 24, present: false },
  { name: "Alexander Lopez", class: "Class 3", id: 25, present: false },
  { name: "Grace Gonzalez", class: "Class 3", id: 26, present: false },
  { name: "Mason Lee", class: "Class 3", id: 27, present: false },
  { name: "Sophia Perez", class: "Class 3", id: 28, present: false },
  { name: "Logan Sanchez", class: "Class 3", id: 29, present: false },
  { name: "Ava Torres", class: "Class 3", id: 30, present: false },

  { name: "Oliver Rivera", class: "Class 4", id: 31, present: false },
  { name: "Lily Nguyen", class: "Class 4", id: 32, present: false },
  { name: "Benjamin Kim", class: "Class 4", id: 33, present: false },
  { name: "Mia Patel", class: "Class 4", id: 34, present: false },
  { name: "Samuel Tran", class: "Class 4", id: 35, present: false },
  { name: "Emma Singh", class: "Class 4", id: 36, present: false },
  { name: "Alexander Choi", class: "Class 4", id: 37, present: false },
  { name: "Isabella Wong", class: "Class 4", id: 38, present: false },
  { name: "Ethan Das", class: "Class 4", id: 39, present: false },
  { name: "Sophia Kim", class: "Class 4", id: 40, present: false },

  { name: "William Garcia", class: "Class 5", id: 41, present: false },
  { name: "Sophia Nguyen", class: "Class 5", id: 42, present: false },
  { name: "James Lee", class: "Class 5", id: 43, present: false },
  { name: "Mia Kim", class: "Class 5", id: 44, present: false },
  { name: "Ethan Patel", class: "Class 5", id: 45, present: false },
  { name: "Emily Tran", class: "Class 5", id: 46, present: false },
  { name: "Alexander Singh", class: "Class 5", id: 47, present: false },
  { name: "Olivia Choi", class: "Class 5", id: 48, present: false },
  { name: "Benjamin Wong", class: "Class 5", id: 49, present: false },
  { name: "Ava Das", class: "Class 5", id: 50, present: false },
];

export default studentsData;
